image: ${GITLAB_CI_REGISTRY}/screamingbunny/docker/plus:centos-python3

variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: clone
  DOCKER_DRIVER: overlay2

stages:
  - build

before_script:
  - REPO=${CI_REPOSITORY_URL#*@}
  - REPO_BASE=${REPO%.com/*}.com
  - REPO_URL=git@${REPO_BASE}:${REPO#*/}
  - yum update -y
  - yum install --disablerepo=epel -y git openssh-clients ca-certificates
  - update-ca-trust force-enable
  - echo "$HII_CA_PUBLIC" | base64 --decode | tr -d '\r' > /etc/pki/ca-trust/source/anchors/hii_ca.crt
  - update-ca-trust extract
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | base64 --decode | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod +x ./.git_ssh
  - cp ./.ssh_config ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - pip config set global.cert /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  - git config user.name "${TRIGGER_USER_NAME:-${GITLAB_USER_NAME:-"GitLab CI"}}"
  - git config user.email "${TRIGGER_USER_EMAIL:-$GITLAB_USER_EMAIL}"
  - git config push.default matching

Build:
  stage: build
  script:
    - git checkout ${CI_COMMIT_REF_NAME:-develop}
    - python3 update_subs.py --verbose --url_base git@${REPO_BASE} --repo_branch ${CI_COMMIT_REF_NAME:-develop}
    - git add --all
    - git commit -m "Update from repo ${TRIGGER_REPO:-"Commit"} - $(date -u +"%F %T %Z") [CI Skip]" && (echo "Pushing as $(git config --get user.name) - $(git config --get user.email)" && git push ${REPO_URL})