version: '3'

volumes:
  etcd:
    labels:
      com.screaming_bunny.container: 'Etcd'
      com.screaming_bunny.description: 'Persistent Etcd Volume'

  database:
    labels:
      com.screaming_bunny.container: 'MariaDB'
      com.screaming_bunny.description: 'Persistent MariaDB Volume'

  queue:
    labels:
      com.screaming_bunny.container: 'RabbitMQ'
      com.screaming_bunny.description: 'Persistent RabbitMQ Volume'

services:
  core:
    hostname: core
    image: oif/orchestrator-core
    build:
      context: ./orchestrator/core
      dockerfile: Dockerfile
    env_file:
      - ./environment/database.connect.env
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
      - ./environment/security.env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 30s
      timeout: 10s
      retries: 5
    external_links:
      - database
      - queue
    depends_on:
      - queue
      - database
    restart: on-failure:5

  core-gui:
    hostname: core-gui
    image: oif/orchestrator-gui
    build:
      context: ./orchestrator/gui
      dockerfile: Dockerfile
    environment:
      ORC_HOST: core
      ORC_PORT: 8080
    ports:
      - 8080:80
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 5
    external_links:
      - core
    depends_on:
      - core
    restart: on-failure:5

  transport-http:
    hostname: transport-http
    image: oif/orchestrator-transport-http
    build:
      context: ./orchestrator/transport/http
      dockerfile: Dockerfile
    env_file:
      - ./environment/queue.connect.env
      - ./environment/security.env
    external_links:
      - queue
    depends_on:
      - queue

  transport-https:
    hostname: transport-https
    image: oif/orchestrator-transport-https
    build:
      context: ./orchestrator/transport/https
      dockerfile: Dockerfile
    env_file:
      - ./environment/queue.connect.env
      - ./environment/security.env
    external_links:
      - queue
    depends_on:
      - queue

  transport-mqtt:
    hostname: transport-mqtt
    image: oif/orchestrator-transport-mqtt
    build:
      context: ./orchestrator/transport/mqtt
      dockerfile: Dockerfile
    env_file:
      - ./environment/queue.connect.env
      - ./environment/etcd.connect.env
      - ./environment/mqtt_transport.env
      - ./environment/security.env
    external_links:
      - queue
    depends_on:
      - queue

  queue:
    hostname: rabbit
    image: rabbitmq:management-alpine
    volumes:
      - queue:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure:5

  database:
    hostname: database
    image: mariadb
    env_file:
      - ./environment/database.env
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ['CMD', '/usr/bin/mysql/install/bin/mysql', '--protocol=tcp', '-h', 'mysql', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD', '-e', '"show databases;"', '||', 'exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure:5

  etcd:
    hostname: etcd
    image: quay.io/coreos/etcd:v3.3.25
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_DATA_DIR: '/data/etcd'
    volumes:
      - etcd:/data/etcd
    command: sh -c 'etcd -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://etcd:2379'
    restart: on-failure:5
